version: "3.9"

services:
  redis:
    image: redis
    restart: always

  webapp:
    restart: always
    build:
      context: ./webapp
    ports:
      - "8000:8000"
    command: [ "python3", "./source/manage.py", "runserver", "0.0.0.0:8000"]

  worker:
    restart: always
    build:
      context: ./webapp
    volumes:
      - ./webapp/source/reports:/app/source/reports
    command: ['celery', '--workdir=./source', '-A', 'proj', 'worker' ]